// packages/vue/src/components/Navigation.vue
<template>
  <!-- Header Navigation -->
  <header v-if="type === 'header'" :class="['nav-header', className]" :style="customStyle">
    <div v-if="$slots.logo" class="nav-header-logo">
      <slot name="logo" />
    </div>
    <nav class="nav-header-menu">
      <a
        v-for="item in items"
        :key="item.id"
        :href="item.href || '#'"
        class="nav-header-item"
        @click="(e) => handleItemClick(e, item)"
      >
        <span v-if="item.icon" class="nav-header-item-icon">{{ item.icon }}</span>
        <span class="nav-header-item-label">{{ item.label }}</span>
      </a>
    </nav>
    <div v-if="$slots.actions" class="nav-header-actions">
      <slot name="actions" />
    </div>
  </header>

  <!-- Sidebar Navigation -->
  <aside v-else :class="['nav-sidebar', { 'is-collapsed': collapsed }, className]" :style="customStyle">
    <nav class="nav-sidebar-menu">
      <NavItem
        v-for="item in items"
        :key="item.id"
        :item="item"
        :active-id="activeId"
        :level="0"
        @item-click="handleItemClick"
      />
    </nav>
    <button
      v-if="collapsible"
      class="nav-sidebar-toggle"
      @click="() => (collapsed = !collapsed)"
      :aria-label="collapsed ? 'Expand sidebar' : 'Collapse sidebar'"
    >
      <svg
        width="16"
        height="16"
        viewBox="0 0 16 16"
        fill="none"
        stroke="currentColor"
        :style="{ transform: collapsed ? 'rotate(180deg)' : 'rotate(0deg)', transition: 'transform 0.2s' }"
      >
        <path d="M10 12L6 8L10 4" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
      </svg>
    </button>
  </aside>
</template>

<script setup lang="ts">
import { ref, defineComponent } from 'vue';

export interface NavItem {
  id: string;
  label: string;
  href?: string;
  icon?: string;
  onClick?: () => void;
  children?: NavItem[];
}

interface Props {
  type?: 'header' | 'sidebar';
  items: NavItem[];
  activeId?: string;
  collapsible?: boolean;
  defaultCollapsed?: boolean;
  className?: string;
  customStyle?: Record<string, any>;
}

const props = withDefaults(defineProps<Props>(), {
  type: 'sidebar',
  collapsible: false,
  defaultCollapsed: false,
  className: '',
  customStyle: () => ({})
});

const emit = defineEmits<{
  'item-click': [item: NavItem];
}>();

const collapsed = ref(props.defaultCollapsed);

const handleItemClick = (e: MouseEvent | Event, item: NavItem) => {
  if (item.onClick || props.type === 'sidebar') {
    e.preventDefault();
  }
  item.onClick?.();
  emit('item-click', item);
};
</script>

<script lang="ts">
// Sidebar Nav Item Component
export default defineComponent({
  name: 'NavItem',
  props: {
    item: { type: Object as () => NavItem, required: true },
    activeId: { type: String },
    level: { type: Number, default: 0 }
  },
  emits: ['item-click'],
  setup(props, { emit }) {
    const isExpanded = ref(false);
    const isActive = props.activeId === props.item.id;
    const hasChildren = props.item.children && props.item.children.length > 0;

    const handleClick = (e: MouseEvent) => {
      if (hasChildren) {
        e.preventDefault();
        isExpanded.value = !isExpanded.value;
      }
      emit('item-click', e, props.item);
    };

    return { isExpanded, isActive, hasChildren, handleClick };
  },
  template: `
    <div class="nav-sidebar-item-wrapper">
      <a
        :href="item.href || '#'"
        :class="['nav-sidebar-item', { 'is-active': isActive, 'has-children': hasChildren }]"
        :style="{ paddingLeft: level * 1.5 + 1 + 'rem' }"
        @click="handleClick"
      >
        <span v-if="item.icon" class="nav-sidebar-item-icon">{{ item.icon }}</span>
        <span class="nav-sidebar-item-label">{{ item.label }}</span>
        <svg
          v-if="hasChildren"
          class="nav-sidebar-item-arrow"
          width="12"
          height="12"
          viewBox="0 0 12 12"
          fill="none"
          stroke="currentColor"
          :style="{ transform: isExpanded ? 'rotate(90deg)' : 'rotate(0deg)', transition: 'transform 0.2s' }"
        >
          <path d="M4 2L8 6L4 10" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
        </svg>
      </a>
      <div v-if="hasChildren && isExpanded" class="nav-sidebar-children">
        <NavItem
          v-for="child in item.children"
          :key="child.id"
          :item="child"
          :active-id="activeId"
          :level="level + 1"
          @item-click="(e, item) => $emit('item-click', e, item)"
        />
      </div>
    </div>
  `
});
</script>

// packages/monochrome-react/src/components/Navigation.tsx
import React, { useState, ReactNode } from 'react';

export interface NavItem {
  id: string;
  label: string;
  href?: string;
  icon?: ReactNode;
  onClick?: () => void;
  children?: NavItem[];
}

export interface NavigationHeaderProps {
  logo?: ReactNode;
  items: NavItem[];
  actions?: ReactNode;
  onItemClick?: (item: NavItem) => void;
  className?: string;
  style?: React.CSSProperties;
}

export const NavigationHeader: React.FC<NavigationHeaderProps> = ({
  logo,
  items,
  actions,
  onItemClick,
  className = '',
  style = {}
}) => {
  const handleItemClick = (item: NavItem) => {
    item.onClick?.();
    onItemClick?.(item);
  };

  return (
    <header className={`nav-header ${className}`} style={style}>
      {logo && <div className="nav-header-logo">{logo}</div>}
      <nav className="nav-header-menu">
        {items.map((item) => (
          <a
            key={item.id}
            href={item.href || '#'}
            className="nav-header-item"
            onClick={(e) => {
              if (item.onClick || onItemClick) {
                e.preventDefault();
                handleItemClick(item);
              }
            }}
          >
            {item.icon && <span className="nav-header-item-icon">{item.icon}</span>}
            <span className="nav-header-item-label">{item.label}</span>
          </a>
        ))}
      </nav>
      {actions && <div className="nav-header-actions">{actions}</div>}
    </header>
  );
};

NavigationHeader.displayName = 'NavigationHeader';

export interface NavigationSidebarProps {
  items: NavItem[];
  activeId?: string;
  collapsible?: boolean;
  defaultCollapsed?: boolean;
  onItemClick?: (item: NavItem) => void;
  className?: string;
  style?: React.CSSProperties;
}

export const NavigationSidebar: React.FC<NavigationSidebarProps> = ({
  items,
  activeId,
  collapsible = false,
  defaultCollapsed = false,
  onItemClick,
  className = '',
  style = {}
}) => {
  const [collapsed, setCollapsed] = useState(defaultCollapsed);
  const [expandedItems, setExpandedItems] = useState<Set<string>>(new Set());

  const handleItemClick = (item: NavItem) => {
    if (item.children) {
      const newExpanded = new Set(expandedItems);
      if (newExpanded.has(item.id)) {
        newExpanded.delete(item.id);
      } else {
        newExpanded.add(item.id);
      }
      setExpandedItems(newExpanded);
    }

    item.onClick?.();
    onItemClick?.(item);
  };

  const renderNavItem = (item: NavItem, level: number = 0) => {
    const isActive = activeId === item.id;
    const isExpanded = expandedItems.has(item.id);
    const hasChildren = item.children && item.children.length > 0;

    return (
      <div key={item.id} className="nav-sidebar-item-wrapper">
        <a
          href={item.href || '#'}
          className={`nav-sidebar-item ${isActive ? 'is-active' : ''} ${hasChildren ? 'has-children' : ''}`}
          style={{ paddingLeft: `${level * 1.5 + 1}rem` }}
          onClick={(e) => {
            if (item.onClick || onItemClick || hasChildren) {
              e.preventDefault();
              handleItemClick(item);
            }
          }}
        >
          {item.icon && <span className="nav-sidebar-item-icon">{item.icon}</span>}
          <span className="nav-sidebar-item-label">{item.label}</span>
          {hasChildren && (
            <svg
              className="nav-sidebar-item-arrow"
              width="12"
              height="12"
              viewBox="0 0 12 12"
              fill="none"
              stroke="currentColor"
              style={{
                transform: isExpanded ? 'rotate(90deg)' : 'rotate(0deg)',
                transition: 'transform 0.2s'
              }}
            >
              <path d="M4 2L8 6L4 10" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          )}
        </a>
        {hasChildren && isExpanded && (
          <div className="nav-sidebar-children">
            {item.children!.map((child) => renderNavItem(child, level + 1))}
          </div>
        )}
      </div>
    );
  };

  return (
    <aside
      className={`nav-sidebar ${collapsed ? 'is-collapsed' : ''} ${className}`}
      style={style}
    >
      <nav className="nav-sidebar-menu">
        {items.map((item) => renderNavItem(item))}
      </nav>
      {collapsible && (
        <button
          className="nav-sidebar-toggle"
          onClick={() => setCollapsed(!collapsed)}
          aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}
        >
          <svg
            width="16"
            height="16"
            viewBox="0 0 16 16"
            fill="none"
            stroke="currentColor"
            style={{
              transform: collapsed ? 'rotate(180deg)' : 'rotate(0deg)',
              transition: 'transform 0.2s'
            }}
          >
            <path d="M10 12L6 8L10 4" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </button>
      )}
    </aside>
  );
};

NavigationSidebar.displayName = 'NavigationSidebar';
