// packages/web-components/src/Tabs.ts
export class MonoTabs extends HTMLElement {
  private activeTab: string = '';
  private tabs: Array<{ id: string; label: string; content: string }> = [];

  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
  }

  connectedCallback(): void {
    this.parseTabs();
    this.render();
  }

  private parseTabs(): void {
    const tabElements = this.querySelectorAll('[slot^="tab-"]');
    this.tabs = Array.from(tabElements).map((el) => {
      const slot = el.getAttribute('slot') || '';
      const id = slot.replace('tab-', '');
      const label = el.getAttribute('data-label') || id;
      return { id, label, content: el.innerHTML };
    });
    if (this.tabs.length > 0 && !this.activeTab) {
      this.activeTab = this.tabs[0].id;
    }
  }

  private render(): void {
    if (!this.shadowRoot) return;

    this.shadowRoot.innerHTML = `
      <link rel="stylesheet" href="/ui/monochrome-edge.css">
      <style>
        :host {
          display: block;
        }
      </style>
      <div class="tabs">
        <div class="tabs-header" role="tablist">
          ${this.tabs.map(tab => `
            <button
              class="tab-btn ${this.activeTab === tab.id ? 'is-active' : ''}"
              data-tab="${tab.id}"
              role="tab"
              aria-selected="${this.activeTab === tab.id}"
            >
              ${tab.label}
            </button>
          `).join('')}
        </div>
        <div class="tabs-content">
          ${this.tabs.map(tab => `
            <div
              class="tab-panel ${this.activeTab === tab.id ? 'is-active' : ''}"
              role="tabpanel"
              ${this.activeTab !== tab.id ? 'hidden' : ''}
            >
              <slot name="tab-${tab.id}">${tab.content}</slot>
            </div>
          `).join('')}
        </div>
      </div>
    `;

    this.attachTabListeners();
  }

  private attachTabListeners(): void {
    const buttons = this.shadowRoot?.querySelectorAll('.tab-btn');
    buttons?.forEach(button => {
      button.addEventListener('click', () => {
        const tabId = button.getAttribute('data-tab');
        if (tabId) {
          this.activeTab = tabId;
          this.render();
          this.dispatchEvent(new CustomEvent('tab-change', {
            detail: { tabId },
            bubbles: true,
            composed: true
          }));
        }
      });
    });
  }
}

customElements.define('mono-tabs', MonoTabs);

// packages/vue/src/components/Tabs.vue
<template>
  <div :class="['tabs', className]" :style="customStyle">
    <div class="tabs-header" role="tablist">
      <button
        v-for="tab in tabs"
        :key="tab.id"
        :class="['tab-btn', { 'is-active': activeTab === tab.id, 'is-disabled': tab.disabled }]"
        @click="() => handleTabClick(tab.id, tab.disabled)"
        :disabled="tab.disabled"
        role="tab"
        :aria-selected="activeTab === tab.id"
        :aria-controls="`tab-panel-${tab.id}`"
      >
        {{ tab.label }}
      </button>
    </div>
    <div class="tabs-content">
      <div
        v-for="tab in tabs"
        :key="tab.id"
        :id="`tab-panel-${tab.id}`"
        :class="['tab-panel', { 'is-active': activeTab === tab.id }]"
        role="tabpanel"
        :hidden="activeTab !== tab.id"
      >
        <slot :name="`tab-${tab.id}`">{{ tab.content }}</slot>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';

export interface TabItem {
  id: string;
  label: string;
  content?: any;
  disabled?: boolean;
}

interface Props {
  tabs: TabItem[];
  defaultActiveId?: string;
  className?: string;
  customStyle?: Record<string, any>;
}

const props = withDefaults(defineProps<Props>(), {
  className: '',
  customStyle: () => ({})
});

const emit = defineEmits<{
  change: [tabId: string];
}>();

const activeTab = ref(props.defaultActiveId || props.tabs[0]?.id);

const handleTabClick = (tabId: string, disabled?: boolean) => {
  if (disabled) return;
  activeTab.value = tabId;
  emit('change', tabId);
};
</script>
