// packages/monochrome-react/src/components/Tabs.tsx
import React, { useState, ReactNode } from 'react';

export interface TabItem {
  id: string;
  label: string;
  content: ReactNode;
  disabled?: boolean;
}

export interface TabsProps {
  tabs: TabItem[];
  defaultActiveId?: string;
  onChange?: (tabId: string) => void;
  className?: string;
  style?: React.CSSProperties;
}

export const Tabs: React.FC<TabsProps> = ({
  tabs,
  defaultActiveId,
  onChange,
  className = '',
  style = {}
}) => {
  const [activeTab, setActiveTab] = useState(defaultActiveId || tabs[0]?.id);

  const handleTabClick = (tabId: string, disabled?: boolean) => {
    if (disabled) return;
    setActiveTab(tabId);
    onChange?.(tabId);
  };

  const activeTabContent = tabs.find(tab => tab.id === activeTab)?.content;

  return (
    <div className={`tabs ${className}`} style={style}>
      <div className="tabs-header" role="tablist">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            className={`tab-btn ${activeTab === tab.id ? 'is-active' : ''} ${tab.disabled ? 'is-disabled' : ''}`}
            onClick={() => handleTabClick(tab.id, tab.disabled)}
            disabled={tab.disabled}
            role="tab"
            aria-selected={activeTab === tab.id}
            aria-controls={`tab-panel-${tab.id}`}
          >
            {tab.label}
          </button>
        ))}
      </div>
      <div className="tabs-content">
        {tabs.map((tab) => (
          <div
            key={tab.id}
            id={`tab-panel-${tab.id}`}
            className={`tab-panel ${activeTab === tab.id ? 'is-active' : ''}`}
            role="tabpanel"
            hidden={activeTab !== tab.id}
          >
            {tab.content}
          </div>
        ))}
      </div>
    </div>
  );
};

Tabs.displayName = 'Tabs';

// packages/vue/src/components/Tabs.vue
<template>
  <div :class="['tabs', className]" :style="customStyle">
    <div class="tabs-header" role="tablist">
      <button
        v-for="tab in tabs"
        :key="tab.id"
        :class="['tab-btn', { 'is-active': activeTab === tab.id, 'is-disabled': tab.disabled }]"
        @click="() => handleTabClick(tab.id, tab.disabled)"
        :disabled="tab.disabled"
        role="tab"
        :aria-selected="activeTab === tab.id"
        :aria-controls="`tab-panel-${tab.id}`"
      >
        {{ tab.label }}
      </button>
    </div>
    <div class="tabs-content">
      <div
        v-for="tab in tabs"
        :key="tab.id"
        :id="`tab-panel-${tab.id}`"
        :class="['tab-panel', { 'is-active': activeTab === tab.id }]"
        role="tabpanel"
        :hidden="activeTab !== tab.id"
      >
        <slot :name="`tab-${tab.id}`">{{ tab.content }}</slot>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';

export interface TabItem {
  id: string;
  label: string;
  content?: any;
  disabled?: boolean;
}

interface Props {
  tabs: TabItem[];
  defaultActiveId?: string;
  className?: string;
  customStyle?: Record<string, any>;
}

const props = withDefaults(defineProps<Props>(), {
  className: '',
  customStyle: () => ({})
});

const emit = defineEmits<{
  change: [tabId: string];
}>();

const activeTab = ref(props.defaultActiveId || props.tabs[0]?.id);

const handleTabClick = (tabId: string, disabled?: boolean) => {
  if (disabled) return;
  activeTab.value = tabId;
  emit('change', tabId);
};
</script>
